//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PurchaseFlow.Schemas.PurchaseResponse")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://PurchaseFlow.Schemas.PurchaseResponse", IsNullable=false)]
public partial class PurchaseResponse {
    
    private uint customerIdField;
    
    private decimal priceField;
    
    private uint visitsField;
    
    private string messageField;
    
    public PurchaseResponse() {
        this.customerIdField = ((uint)(0));
        this.priceField = ((decimal)(0m));
        this.visitsField = ((uint)(0));
    }
    
    /// <remarks/>
    public uint customerId {
        get {
            return this.customerIdField;
        }
        set {
            this.customerIdField = value;
        }
    }
    
    /// <remarks/>
    public decimal price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    public uint visits {
        get {
            return this.visitsField;
        }
        set {
            this.visitsField = value;
        }
    }
    
    /// <remarks/>
    public string message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
}
