//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClient.Purchase {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Purchase.PurchaseOrchestrations_PurchaseOrchestartion_PurchasePort")]
    public interface PurchaseOrchestrations_PurchaseOrchestartion_PurchasePort {
        
        // CODEGEN: Generating message contract since the operation Operation_1 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="Operation_1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WcfClient.Purchase.Operation_1Response Operation_1(WcfClient.Purchase.Operation_1Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PurchaseFlow.Schemas.PurchaseRequest")]
    public partial class PurchaseRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private uint customerIdField;
        
        private uint productIdField;
        
        private uint quantityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public uint customerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("customerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public uint productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("productId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public uint quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("quantity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Operation_1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://PurchaseFlow.Schemas.PurchaseRequest", Order=0)]
        public WcfClient.Purchase.PurchaseRequest PurchaseRequest;
        
        public Operation_1Request() {
        }
        
        public Operation_1Request(WcfClient.Purchase.PurchaseRequest PurchaseRequest) {
            this.PurchaseRequest = PurchaseRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Operation_1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://PurchaseFlow.Schemas.PurchaseRequest", Order=0)]
        public WcfClient.Purchase.PurchaseRequest PurchaseRequest;
        
        public Operation_1Response() {
        }
        
        public Operation_1Response(WcfClient.Purchase.PurchaseRequest PurchaseRequest) {
            this.PurchaseRequest = PurchaseRequest;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PurchaseOrchestrations_PurchaseOrchestartion_PurchasePortChannel : WcfClient.Purchase.PurchaseOrchestrations_PurchaseOrchestartion_PurchasePort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PurchaseOrchestrations_PurchaseOrchestartion_PurchasePortClient : System.ServiceModel.ClientBase<WcfClient.Purchase.PurchaseOrchestrations_PurchaseOrchestartion_PurchasePort>, WcfClient.Purchase.PurchaseOrchestrations_PurchaseOrchestartion_PurchasePort {
        
        public PurchaseOrchestrations_PurchaseOrchestartion_PurchasePortClient() {
        }
        
        public PurchaseOrchestrations_PurchaseOrchestartion_PurchasePortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PurchaseOrchestrations_PurchaseOrchestartion_PurchasePortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseOrchestrations_PurchaseOrchestartion_PurchasePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseOrchestrations_PurchaseOrchestartion_PurchasePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfClient.Purchase.Operation_1Response WcfClient.Purchase.PurchaseOrchestrations_PurchaseOrchestartion_PurchasePort.Operation_1(WcfClient.Purchase.Operation_1Request request) {
            return base.Channel.Operation_1(request);
        }
        
        public void Operation_1(ref WcfClient.Purchase.PurchaseRequest PurchaseRequest) {
            WcfClient.Purchase.Operation_1Request inValue = new WcfClient.Purchase.Operation_1Request();
            inValue.PurchaseRequest = PurchaseRequest;
            WcfClient.Purchase.Operation_1Response retVal = ((WcfClient.Purchase.PurchaseOrchestrations_PurchaseOrchestartion_PurchasePort)(this)).Operation_1(inValue);
            PurchaseRequest = retVal.PurchaseRequest;
        }
    }
}
